version: "2"
authtoken: 2gJh4RVxzdTGWGei4Tc8uY4v2uZ_4LX348dsDENMaKzMA5wnF

tunnels:
  flask_api:
    addr: 5000
    proto: http
    inspect: false  # Optional: Disable request inspection

  node_web_app:
    addr: 4000
    proto: http
    inspect: false  # Optional: Disable request inspection
